// SampleAtlProj.idl : IDL source for SampleAtlProj
//

// This file will be processed by the MIDL tool to
// produce the type library (SampleAtlProj.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(f6ca04e1-aec6-4d29-be00-e528f73f3f8c),
	pointer_default(unique)
]
interface IMyMathComponent : IUnknown
{
	HRESULT AddFunc([in] int iVal1, [in] int iVal2, [out] int* iAddValue);
};


[
	object,
	uuid(bd458f21-d304-4eb1-a0c4-fcc9d6765d40),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IAutomationObject : IDispatch
{
	[id(1)] HRESULT DisplayMessage([in] BSTR strMessage);
};
[
	object,
	uuid(fbf36eb2-e39e-4a9f-9e43-428703259631),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ILateBindingObject : IDispatch
{
	
	[id(1), helpstring("SquareOfNumber")] HRESULT SquareOfNumber([in] int nVal, [out] int* nResult);
};
[
	object,
	uuid(c5b1ee1f-5782-42e8-b504-12120254fbdd),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ISafeArrayComponent : IDispatch
{
	[id(1)] HRESULT AddNumbers([in] VARIANT theArray, [out] LONG* lSum);
};
[
	uuid(a789f004-6c0d-4a1f-aecc-d5400e78ab9a),
	version(1.0),
]
library SampleAtlProjLib
{
	importlib("stdole2.tlb");
	[
		uuid(f19a3069-fe55-42e7-98e1-79c81abd8b00)
	]
	coclass MyMathComponent
	{
		[default] interface IMyMathComponent;
	};

	[
		uuid(8e6013f7-6083-4413-a570-70bdfeacbe98)
	]
	coclass AutomationObject
	{
		[default] interface IAutomationObject;
	};
	[
		uuid(8db59fc5-1a14-45fc-a7a3-520d8e31dbbc)
	]
	coclass LateBindingObject
	{
		[default] interface ILateBindingObject;
	};
	[
		uuid(d23c735d-3837-4722-a548-18614a58aa74)
	]
	coclass SafeArrayComponent
	{
		[default] interface ISafeArrayComponent;
	};
};

import "shobjidl.idl";
import "shobjidl.idl";
import "shobjidl.idl";
import "shobjidl.idl";
