import "oaidl.idl";
import "ocidl.idl";
//SYntax to include external IDL files....

[
	object, //Its a COM interface object
	uuid(83F772E8-E4F6-454A-B5B8-2696EB59A976)
]
//All interfaces in COM are to be derived from IUnknown....
//All Methods of COM are to return a 32 Bit Error Code called HRESULT. 
interface IAddComponent : IUnknown {
	HRESULT AddFunc(int iVal1, int iVal2, int* iRes);//Any return value will be by Reference or Pointer....
};

[
	object, //Its a COM interface object
	uuid(32CDEC12-C813-4129-A6E6-4BC7F7A77BE9)
]
interface ISubComponent : IUnknown {
	HRESULT SubFunc(int iVal1, int iVal2, int* iRes);
};

[
	uuid(493CCF44-535F-4252-B202-3F3D2736F2BF),
	version(1.0)
]
library SampleComDllLib {
	importlib("stdole32.tlb");
	[
		uuid(31F00913-EA5D-4445-B16B-67D3B83E6745)
	]
		coclass MathComponent {
		[default]
			interface IAddComponent;
		interface ISubComponent;
	};
};

