using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SampleAtlProjLib;
namespace CSharpComClient
{
    internal class Program
    {
        static void Main(string[] args)
        {
            //SquareNumbersExample();
            SafeArrayExample();
        }

        private static void SafeArrayExample()
        {
            try
            {
                ISafeArrayComponent com = new SafeArrayComponentClass();
                object values = new int[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
                int result = 0;
                com.AddNumbers(values, out result);
                Console.WriteLine("The sum of elements in the array is " + result);
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }

        private static void SquareNumbersExample()
        {
            IAutomationObject automationObject = new AutomationObjectClass();//For every COM Component called CX, a Runtime Callable Wrapper(RCW) class called XClass will be generated by .NET Framework. 
            automationObject.DisplayMessage("Apple 123");

            ILateBindingObject bindingObject = new LateBindingObjectClass();
            int result = 0;
            bindingObject.SquareOfNumber(123, out result);
            Console.WriteLine("The Result is " + result);
        }
    }
}
